# 1. Configurações da Aplicação
spring.application.name=biblioteca-api
server.port=8080

# 2. Conexão com PostgreSQL
# Certifique-se de criar o banco 'biblioteca' no seu pgAdmin antes de rodar
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driverClassName=org.postgresql.Driver

# 3. Configurações do JPA / Hibernate
# 'update' cria/altera as tabelas automaticamente conforme suas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 4. Configurações do H2 (Desabilitado para evitar conflitos, mas deixei a console caso precise testar)
spring.h2.console.enabled=false

# 5. Configurações do Swagger (Caminho da documentação)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# 6. Inicialização de Scripts (Desabilitado por enquanto para evitar erros no data.sql)
spring.sql.init.mode=never

# 7. Configurando desativar a segurança temporariamente, para conseguir acessar o H2 Console.
spring.security.user.name=admin
spring.security.user.password=admin